/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://bldddzvryvhgxawmwf2hd7dxya.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yz4k53syfjd2vkbsqo42ofa7i4"
};


export default awsconfig;
